/*
 * app_config.h
 *
 * Application-level tuning: rates, task priorities, stack sizes.
 *
 * Kernel configuration (tick rate, heap, hooks) comes from the FreeRTOSConfig.h
 * generated by the BSP; the stage Readme lists the settings this code relies
 * on, and main.c checks the ones that can be checked at build time.
 */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "FreeRTOS.h"
#include "task.h"

#define APP_FW_VERSION              "0.2.0"

/* ---- sampling -------------------------------------------------------- */

#define APP_SAMPLE_RATE_HZ          10U     /* TTC interrupt rate -> 100 ms sample period */

/*
 * How long the producer waits for a timer tick before it counts a timeout.
 * Three periods: never trips on jitter, but a dead timer still shows up in
 * the diagnostics within a fraction of a second.
 */
#define APP_SAMPLE_TIMEOUT_MS       ((3U * 1000U) / APP_SAMPLE_RATE_HZ)

/* ---- consumer -------------------------------------------------------- */

#define APP_HEARTBEAT_SAMPLES       5U      /* LD4 toggles every 5 samples: 1 Hz blink at 10 Hz sampling */
#define APP_SLOW_STREAM_DIVIDER     10U     /* slow stream mode prints every 10th sample                 */
#define APP_STALL_WARN_MS           1000U   /* no sample for this long -> warning on the console          */

/* ---- UI -------------------------------------------------------------- */

#define APP_UI_SCAN_PERIOD_MS       10U     /* button debounce scan and UART RX poll */

/* ---- priorities -------------------------------------------------------
 *
 * Producer on top, so sample timing depends only on the ISR and on itself.
 * UI above the consumer, so key presses and buttons are picked up even while
 * a long report is going out. Consumer at the bottom: it busy-waits on the
 * UART TX FIFO and must never hold anything else up.
 *
 * The gaps are intentional - later stages slot tasks in between.
 */
#define APP_PRIO_PRODUCER           (tskIDLE_PRIORITY + 4U)
#define APP_PRIO_UI                 (tskIDLE_PRIORITY + 2U)
#define APP_PRIO_CONSUMER           (tskIDLE_PRIORITY + 1U)

/* ---- stacks, in words (4 bytes each) ----------------------------------
 *
 * The consumer gets the most: newlib's vsnprintf() is stack hungry. These
 * are first guesses with margin - check the headroom with 'd' after a few
 * minutes of running and trim.
 */
#define APP_STACK_PRODUCER          512U
#define APP_STACK_UI                512U
#define APP_STACK_CONSUMER          1024U

#endif /* APP_CONFIG_H */
