/*
 * app_config.h
 *
 * Application-level tuning: rates, task priorities, stack sizes.
 *
 * Kernel configuration (tick rate, heap, hooks) comes from the FreeRTOSConfig.h
 * generated by the BSP; the stage Readme lists the settings this code relies
 * on, and main.c checks the ones that can be checked at build time.
 */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "FreeRTOS.h"
#include "task.h"

#define APP_FW_VERSION              "0.4.0"

/* ---- sampling -------------------------------------------------------- */

#define APP_SAMPLE_RATE_HZ          10U     /* TTC interrupt rate -> 100 ms sample period */

/*
 * How long the producer waits for a timer tick before it counts a timeout.
 * Three periods: never trips on jitter, but a dead timer still shows up in
 * the diagnostics within a fraction of a second.
 */
#define APP_SAMPLE_TIMEOUT_MS       ((3U * 1000U) / APP_SAMPLE_RATE_HZ)

/* ---- sensor log (ring buffer in DDR) ----------------------------------
 *
 * Capacity must be a power of two. 4096 records x 32 bytes = 128 KiB, which
 * holds 409.6 s (about 6.8 minutes) of samples at 10 Hz before the oldest get
 * overwritten. Drop it to 256 (25.6 s) to see overwriting quickly on the
 * bench.
 */
#define APP_LOG_CAPACITY            4096U

/*
 * Mutex waits. The producer's is kept far below one sample period: a reader
 * that sits on the lock may cost it a sample, but never its timing. The
 * consumer has nothing time-critical and can afford to wait longer.
 */
#define APP_LOG_WRITE_WAIT_MS       20U
#define APP_LOG_READ_WAIT_MS        100U

/* Records copied per lock. Bounds the mutex hold time on the read side. */
#define APP_LOG_READ_BATCH          16U

/* Batches per consumer pass before it looks at its queue again. */
#define APP_LOG_DRAIN_BATCHES_MAX   4U

/*
 * Bring-up only, 0 in normal builds: busy-wait this many microseconds while
 * holding the log mutex on every read, to make lock contention and priority
 * inheritance visible. The banner warns when it is non-zero.
 */
#define APP_TEST_LOG_HOLD_US        0U

/* ---- consumer -------------------------------------------------------- */

#define APP_CONSUMER_QUEUE_LEN      16U     /* control messages, not data - samples live in the log      */
#define APP_CONSUMER_POLL_MS        250U    /* longest gap between log drains, even without a doorbell    */
#define APP_HEARTBEAT_SAMPLES       5U      /* LD4 toggles every 5 samples: 1 Hz blink at 10 Hz sampling */
#define APP_SLOW_STREAM_DIVIDER     10U     /* slow stream mode prints every 10th sample                 */
#define APP_STALL_WARN_MS           1000U   /* producer made no progress this long -> console warning     */

/* ---- UI -------------------------------------------------------------- */

#define APP_UI_SCAN_PERIOD_MS       10U     /* button debounce scan and UART RX poll */

/* ---- watchdog ---------------------------------------------------------
 *
 * The supervisor task checks every APP_WDT_CHECK_PERIOD_MS that each task
 * checked in within its limit, and only then kicks the SWDT. Limits are
 * several times each task's normal loop period; the consumer's allows for
 * a long report or a backlog drain.
 *
 * Worst case from a hang to the reset: limit + check period + SWDT timeout.
 */
#define APP_WDT_ENABLE              1       /* 0 while debugging with breakpoints */
#define APP_WDT_TIMEOUT_MS          2000U
#define APP_WDT_CHECK_PERIOD_MS     250U
#define APP_WDT_LIMIT_PRODUCER_MS   500U    /* 5 sample periods */
#define APP_WDT_LIMIT_UI_MS         500U
#define APP_WDT_LIMIT_CONSUMER_MS   2000U

/* Terminal keys 1-4 deliberately hang a task. Bring-up only - set to 0 for a release build. */
#define APP_WDT_TEST_COMMANDS       1

/* ---- priorities -------------------------------------------------------
 *
 * Watchdog supervisor above everything, so a busy loop in any other task
 * can't stop it from noticing. Producer next, so sample timing depends only
 * on the ISR and on itself. UI above the consumer, so key presses and buttons
 * are picked up even while a long report is going out. Consumer at the
 * bottom: it busy-waits on the UART TX FIFO and must never hold anything
 * else up.
 */
#define APP_PRIO_WATCHDOG           (tskIDLE_PRIORITY + 5U)
#define APP_PRIO_PRODUCER           (tskIDLE_PRIORITY + 4U)
#define APP_PRIO_UI                 (tskIDLE_PRIORITY + 2U)
#define APP_PRIO_CONSUMER           (tskIDLE_PRIORITY + 1U)

/* ---- stacks, in words (4 bytes each) ----------------------------------
 *
 * The consumer gets the most: newlib's vsnprintf() is stack hungry. These
 * are first guesses with margin - check the headroom with 'd' after a few
 * minutes of running and trim.
 */
#define APP_STACK_WATCHDOG          512U
#define APP_STACK_PRODUCER          512U
#define APP_STACK_UI                512U
#define APP_STACK_CONSUMER          1024U

#endif /* APP_CONFIG_H */
